version: '2'
services:
    term_audit_ao-app:
        image: term_audit_ao
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://term_audit_ao-mysql:3306/term_audit_ao?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    term_audit_ao-mysql:
        extends:
            file: mysql.yml
            service: term_audit_ao-mysql
